insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Ham - Virginia', 40.6);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Mushroom - Shitake, Dry', 38.12);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Asparagus - Green, Fresh', 28.96);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Yokaline', 97.8);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Chicken Breast Halal', 66.33);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Tumeric', 62.82);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Lettuce - Arugula', 73.67);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Juice - Pineapple, 341 Ml', 2.64);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Milk - Skim', 41.02);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Stainless Steel Cleaner Vision', 33.66);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Wine - Jafflin Bourgongone', 71.09);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Pan Grease', 10.9);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Veal - Nuckle', 98.36);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Lemons', 86.43);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Towels - Paper / Kraft', 10.15);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Seaweed Green Sheets', 23.9);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Extract - Almond', 56.72);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Veal - Chops, Split, Frenched', 98.71);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Magnotta Bel Paese Red', 53.99);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Oil - Shortening,liqud, Fry', 38.31);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Container - Clear 16 Oz', 97.02);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Island Oasis - Magarita Mix', 53.71);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Broom - Angled', 15.78);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Ice Cream Bar - Rolo Cone', 28.37);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Oil - Shortening,liqud, Fry', 81.0);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Veal - Kidney', 78.79);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Carbonated Water - Blackcherry', 74.85);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Numi - Assorted Teas', 70.84);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Worcestershire Sauce', 41.13);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Island Oasis - Raspberry', 74.98);
